[tool.poetry]
name = "universal-portfolios"
version = "0.4.0"
description = ""
authors = ["Marigold <mojmir.vinkler@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.1.1"
cvxopt = "^1.2.5"
scipy = "^1.5.2"
matplotlib = "^3.3.1"
pandas-datareader = "^0.9.0"
statsmodels = "^0.12.0"
scikit-learn = "^0.23.2"
seaborn = "^0.10.1"
requests = "^2.24.0"
plotly = "^4.9.0"

[tool.poetry.dev-dependencies]
pytest = "^6.0.1"
ipdb = "^0.13.3"
line-profiler = "^3.0.2"
ipykernel = "^5.3.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
